name: Build on PR

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - 'dev'
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Building with dotnet
        working-directory: .
        run: dotnet build --configuration Release
      - name: Running tests
        working-directory: .
        run: dotnet test
